Inpaint en preklepy
114, 240, 316, 765 add
Obrázky - neviem, ci dirt je naj popis, taktiez viackrat and v jednej vete
Inpaint en spatne popisy
27 nebežia
33 nie je naplnená, ani filled
123 divna zena :grinning:
575 neukazuje obrazok
206 nema klobuk
211 ten stlp nie je zeleny
214 nie je zaparkovany, ale v pohybe
222 ten plot nie je biely
252 nie su tam graffiti
265 ziadna poza, pretoze on bezi
369 nie veľmi funny
425 listy nie prach
685 nevidim pro milk
730 ? ball
828 nie su cierne
831 macka je oranzova
861 right way
895 nie je zlta